version: '3.8'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: tcf3_kafka_ui
    ports:
      - "8090:8080"
    networks:
      - kafka-net
    environment:
      KAFKA_CLUSTERS_0_NAME: tcf3-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

networks:
  kafka-net:
    external: true
